### ISSUE TITLE
Account actions

### ISSUE THREAD

**Issue by Nate-Schaefer** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_003#11]
As a player, to make the game more convenient for myself, I want to have proper account functionality, such as resetting password, logging out and logging back in, etc.

**Comment by elipaulsen** [comment]
half done

**Comment by elipaulsen** [comment]
forgot and password reset done will need to push env vars to heroku in order to work on prod

**Comment by elipaulsen** [comment]
login/logout works and user can reset password by requesting a rest link, which generates a token that expires in 1 hour
