### ISSUE TITLE
In-game shop

### ISSUE THREAD

**Issue by Nate-Schaefer** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_003#12]
As a rich player, to enhance my gaming experience, I want to be able to buy customization items from an in-game shop

**Comment by Nick-Hageman** [comment]
Creating new page for the shop, worked on the UI with animations for weapons/consumables. Opened PR so we can get multiple people working with this page (ex: Shaun adding generative AI sprites) under the avatar tab. Working on adding database functionality for each user's inventory.

**Comment by Nick-Hageman** [comment]
Created an in-game shop, added weapons, consumables, etc. ✔️
