### ISSUE TITLE
Friend System

### ISSUE THREAD

**Issue by Nate-Schaefer** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_003#14]
As a social player, to remember others that I played with, or my IRL friends, I want to have a friend system in the game, so that I can play with them

**Comment by Nate-Schaefer** [comment]
Making the tests for this are kinda trouble, anyone good with factories for testing?

**Comment by ShaunRichter** [comment]
I can take a look

**Comment by Nate-Schaefer** [comment]
PR up for this!
