### ISSUE TITLE
Display user avatars on grid pieces

### ISSUE THREAD

**Issue by Nick-Hageman** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_003#61]
As a player, I want to be able to see what tile I'm currently on. I also want to see what tiles the other players are currently on.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the grid.html.erb file to highlight the current player's position and show other players' positions on the grid. Updated the JavaScript to handle the highlighting of positions.

You can review changes in this commit: https://github.com/mnmnk43434/uiowahjmjohnsonselt2024-projectdirectory-selt_2024_team_003-61/commit/cea3c1b9289937705f5ecc8225cea945b58ffb5d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
